### PR TITLE
Check that network context is still open after waiting for socket

### LINKED ISSUE #155: ClosedIllegalStateException in RemoteConnector if socketReconnector is triggered
HostConnector installs the following `socketReconnector` on `NetworkContext`:
```
                .socketReconnector(new ClosableRunnable() {
                    @Override
                    public void run() {
                        close();
                        if (!eventLoop.isClosing())
                            connect();
                    }

    public synchronized void close() {
        ...
        closeQuietly(nc);
        this.nc = null;
    }
```

If it is triggered while `RCEventHandler` is opening connection, it is possible to get the following unhandled exception:
```
2021-11-18T00:13:45.140 [main/map-cluster-0-blocking-event-loop-11] WARN  n.o.c.n.RemoteConnector$RCEventHandler - 452dc273 threw
net.openhft.chronicle.core.io.ClosedIllegalStateException: software.chronicle.enterprise.map.cluster.MapClusterNetworkContext closed
        at net.openhft.chronicle.core.io.AbstractCloseable.throwExceptionIfClosedInSetter(AbstractCloseable.java:259)
        at net.openhft.chronicle.network.VanillaNetworkContext.throwExceptionIfClosedInSetter(VanillaNetworkContext.java:80)
        at net.openhft.chronicle.network.VanillaNetworkContext.socketChannel(VanillaNetworkContext.java:72)
        at net.openhft.chronicle.network.RemoteConnector$RCEventHandler.action(RemoteConnector.java:172)
        at net.openhft.chronicle.threads.BlockingEventLoop$Runner.run(BlockingEventLoop.java:180)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:104)
```

### PR DESCRIPTION
**Pull request by alamar**
fixes #155

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/network/RemoteConnector.java [hunk 1]
```diff
@@ -168,6 +168,13 @@ public boolean action() throws InvalidEventHandlerException {
...
                     return false;
 
+                if (nc.isClosed()) {
+                    // may be already closed by socketReconnector in HostConnector
+                    closeSocket(sc);
+
+                    throw InvalidEventHandlerException.reusable();
+                }
+
                 nc.socketChannel(sc);
```
Comment (glukos) [inline src/main/java/net/openhft/chronicle/network/RemoteConnector.java:172]: Next calls still can throw `ClosedIllegalStateException` if `nc` can be closed concurrently.
It looks safer to do this in `ClosedIllegalStateException`'s catch block.

**Review by glukos — CHANGES_REQUESTED** [review]

File: src/main/java/net/openhft/chronicle/network/RemoteConnector.java (hunk 1 above)
Comment (alamar) [reply src/main/java/net/openhft/chronicle/network/RemoteConnector.java:172]: Can you check now? The impact is greater if the check is moved to catch block.

**Review by glukos — APPROVED** [review]
