### PR TITLE
Throw ClosedChannelException when FastJ8SocketChannel.read() fails due to underlying channel being closed

### LINKED ISSUE #214: IOException thrown when a read from a FastJ8SocketChannel fails due to the underying channel being closed
It should throw `ClosedChannelException` like the other implementations do (this is handled in lots of places)

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #214

The ClosedChannelException is handled specially in e.g. TcpEventHandler, whereas the generic IOException ends up being logged.

We could perhaps also fix this by checking before we attempt to read from the channel, but that would leave room for a race condition, and potentially re-introduce some of the slowness this class attempts to avoid.

This approach just changes the exception after the error has occurred.

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/network/tcp/FastJ8SocketChannel.java [hunk 1]
```diff
@@ -99,17 +100,27 @@ public int write(ByteBuffer byteBuffer) throws IOException {
...
+                open = false;
+            return ret;
+        } catch (IOException e) {
+            if (!super.isOpen()) {
+                open = false;
+                final ClosedChannelException closedChannelException = new ClosedChannelException();
+                closedChannelException.initCause(e);
+                throw closedChannelException;
+            }
+            throw e;
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/tcp/FastJ8SocketChannel.java]: could make this try/catch block more localised? I don't know if anything else in there throws an IOException

**Review by JerryShea — APPROVED** [review]
beautiful

File: src/main/java/net/openhft/chronicle/network/tcp/FastJ8SocketChannel.java [hunk 2]
```diff
@@ -47,7 +47,7 @@ public int read(ByteBuffer buf) throws IOException {
         if (buf == null)
             throw new NullPointerException();
 
-        if (isBlocking() || isClosed() || !IOTools.isDirectBuffer(buf))
+        if (isBlocking() || isClosed() || !IOTools.isDirectBuffer(buf) || !super.isOpen())
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/tcp/FastJ8SocketChannel.java:50]: Just means we don't attempt the "fast read" if we know the channel isn't open. The slow read behaves as you'd expect (throwing the ClosedChannelException when the channel is closed).

Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/network/tcp/FastJ8SocketChannel.java:50]: The fast read throws an IOException from some com.sun package about an invalid file handle under those circumstances

Comment (nicktindall) [reply src/main/java/net/openhft/chronicle/network/tcp/FastJ8SocketChannel.java:50]: Probably still a chance we throw the IOException if the disconnect happens between the check and the read (though not sure if that can even happen), but it's substantially reduced.
