### PR TITLE
Remove WritableSubHandlers when they reject

### LINKED ISSUE #157: When WritableSubHandlers are removed from an UberHandler they are left in the writers list
If a WritableSubHandler throws a RejectedHandlerException, or any other scenario that leads to them being removed, the removal leaves them in the list of writers so onWrite continues to be called despite the handler being removed for receiving messages.

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #157

I noticed this when working on ChronicleEnterprise/Chronicle-Queue-Enterprise#278

### CODE REVIEW

File: src/test/java/net/openhft/chronicle/network/UberHandlerTest.java [hunk 1]
```diff
@@ -237,6 +240,92 @@ public void testBusyWritingHandlersAreCalledFirstInRoundRobin() throws IOExcepti
...
+        }
+
+        @Override
+        public void onWrite(WireOut outWire) {
+            if (hasRejected) {
+                REJECTED_HANDLER_ONWRITE_CALLED.set(true);
+            }
+        }
+    }
+
```
Comment (nicktindall) [inline src/test/java/net/openhft/chronicle/network/UberHandlerTest.java:328]: Would have loved to have written this as a unit test instead, but the structure of these classes make that tricky

**Review by JerryShea — APPROVED** [review]
