### PR TITLE
Don't trigger reconnect from HeartbeatCheckHandler

### LINKED ISSUE #240: When a reconnection is triggered by the HeartbeatCheckHandler it can result in reconnects being aborted
The socketReconnector being triggered from the HeartbeatCheckHandler kicks off the reconnection on the blocking event loop, and then closes the associated UberHandler which in-turn closes the network context.

When the TcpHandler executes next time it will throw an InvalidEventHandler exception because of the closed socketChannel, which will cause it to be removed from the event loop and its close method to be called.

In the TcpEventHandler close method it calls `socketReconnector().close()` on the old socketReconnector, which itself calls HostConnector.close (which isn't really a close method it's more of a reset method).

The problem is by the time this happens, it's possible we've populated the HostConnector with the new NetworkContext (the one created for the reconnection). So when the reconnection happens and we attempt to set the socketChannel on it, it throws a ClosedIllegalState exception, which causes the RCEventHandler to  be silently removed from the event loop, with no reconnect scheduled.

This leaves the node in a state where it is disconnected and not attempting reconnection. :sweat:

### PR DESCRIPTION
**Pull request by nicktindall**
Reproduce and fix #240 

Depends on https://github.com/OpenHFT/Chronicle-Test-Framework/pull/35

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/network/RemoteConnector.java [hunk 1]
```diff
@@ -174,7 +174,7 @@ public boolean action() throws InvalidEventHandlerException {
                 eventHandler = tcpHandlerSupplier.apply(nc);
 
             } catch (ClosedIllegalStateException e) {
-                Jvm.debug().on(getClass(), "Already closed while connecting to " + address, e);
+                Jvm.warn().on(getClass(), "Already closed while connecting to " + address, e);
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/RemoteConnector.java:177]: This would have been easier to diagnose if it were in the logs

File: src/main/java/net/openhft/chronicle/network/TcpEventHandler.java [hunk 2]
```diff
@@ -197,6 +197,11 @@ public boolean action() throws InvalidEventHandlerException {
         if (tcpHandler == null)
             return false;
 
+        if (tcpHandler.hasTimedOut()) {
+            closeAndStartReconnector();
+            return false;
+        }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/TcpEventHandler.java:203]: We MUST close the TcpEventHandler prior to starting the reconnector, that's why we couldn't do it from HeartbeatCheckHandler, it has no reference to the TcpEventHandler

File: src/main/java/net/openhft/chronicle/network/cluster/handlers/HeartbeatHandler.java [hunk 3]
```diff
@@ -145,10 +145,6 @@ public void close() {
                 }
             }
             lastTimeMessageReceived = Long.MAX_VALUE;
-            Closeable closable = closable();
-            if (closable != null && !closable.isClosed()) {
-                Closeable.closeQuietly(closable);
-            }
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/cluster/handlers/HeartbeatHandler.java:151]: Don't close the UberHandler here, it will be closed by the TcpEventHandler when it closes

File: src/main/java/net/openhft/chronicle/network/cluster/handlers/HeartbeatHandler.java [hunk 4]
```diff
@@ -224,24 +225,16 @@ public String toString() {
...
-                    if (socketReconnector == null)
-                        Jvm.warn().on(getClass(), "socketReconnector == null");
-                    else
-                        socketReconnector.run();
-
-                    HeartbeatHandler.this.close();
-
-                    throw newClosedInvalidEventHandlerException();
+                    HeartbeatHandler.this.hasTimedOut = true;
+                    throw InvalidEventHandlerException.reusable();
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/cluster/handlers/HeartbeatHandler.java:238]: Just set `hasTimedOut` to true, and stop checking for timeouts. The rest of the flow will be taken care of by the TcpEventHandler

**Review by JerryShea — APPROVED** [review]

File: src/test/java/net/openhft/chronicle/network/util/proxy/ProxyConnection.java [hunk 5]
```diff
@@ -0,0 +1,78 @@
+package net.openhft.chronicle.network.util.proxy;
```
Comment (JerryShea) [inline src/test/java/net/openhft/chronicle/network/util/proxy/ProxyConnection.java]: internal
