### PR TITLE
Eagerly load ThreadLogTypeElapsedRecord

### LINKED ISSUE #170: Possible class loading delay in TcpEventHandler
When non-blocking read/write delay warnings are turned on, there is the possibility of a long class loading delay being introduced in the event loop the first time one occurs (this was reported by a client, see stacktrace below).

```
2022-01-21 14:49:12.868 [main/xxx~monitor] INFO  net.openhft.chronicle.threads.MediumEventLoop - xxx-event-loop thread has blocked for 4012.3 ms.
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.openhft.chronicle.network.TcpEventHandler.readAction(TcpEventHandler.java:243)
        at net.openhft.chronicle.network.TcpEventHandler.action0(TcpEventHandler.java:211)
        at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:185)
        at net.openhft.chronicle.threads.MediumEventLoop.runAllMediumHandler(MediumEventLoop.java:359)
        at net.openhft.chronicle.threads.MediumEventLoop.runLoop(MediumEventLoop.java:288)
        at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:247)

2022-01-21 14:49:13.021 [main/yyy~monitor] INFO  net.openhft.chronicle.threads.MediumEventLoop - yyy-event-loop thread has blocked for 4152.0 ms.
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        at net.openhft.chronicle.network.TcpEventHandler.readAction(TcpEventHandler.java:243)
        at net.openhft.chronicle.network.TcpEventHandler.action0(TcpEventHandler.java:211)
        at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:185)
        at net.openhft.chronicle.threads.MediumEventLoop.runAllHandlers(MediumEventLoop.java:418)
        at net.openhft.chronicle.threads.MediumEventLoop.runLoop(MediumEventLoop.java:289)
        at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:247)
```

### PR DESCRIPTION
**Pull request by nicktindall**
Fixes #170

### CODE REVIEW

File: src/main/java/net/openhft/chronicle/network/TcpEventHandler.java [hunk 1]
```diff
@@ -609,6 +612,14 @@ public int read(@NotNull final ChronicleSocketChannel socketChannel, @NotNull fi
         private final LogType logType;
         private final long elapsedNs;
 
+        /**
+         * Does nothing, just called to load the class eagerly
+         * <p>
+         * We have observed lengthy class loading delays due to this class not being loaded
+         */
+        public static void loadClass() {
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/network/TcpEventHandler.java]: private?

File: src/main/java/net/openhft/chronicle/network/TcpEventHandler.java [hunk 2]
```diff
@@ -149,6 +149,9 @@ public TcpEventHandler(@NotNull final T nc, final TcpHandlerBias bias) {
         readLog = new NetworkLog(this.sc, "read");
         writeLog = new NetworkLog(this.sc, "write");
         nbWarningEnabled = Jvm.warn().isEnabled(getClass());
+        if (nbWarningEnabled) {
```
Comment (nicktindall) [inline src/main/java/net/openhft/chronicle/network/TcpEventHandler.java]: Not sure if this will prevent unnecessary class loading... I _think_ it should only load the class if the branch is taken?

Comment (JerryShea) [reply src/main/java/net/openhft/chronicle/network/TcpEventHandler.java]: I am more concerned about concise code TBH

File: src/main/java/net/openhft/chronicle/network/TcpEventHandler.java [hunk 3]
```diff
@@ -74,6 +74,7 @@
     public static boolean DISABLE_TCP_NODELAY = Jvm.getBoolean("disable.tcp_nodelay");
 
     static {
+        ThreadLogTypeElapsedRecord.loadClass();
```
Comment (JerryShea) [inline src/main/java/net/openhft/chronicle/network/TcpEventHandler.java:77]: nice

**Review by JerryShea — APPROVED** [review]

File: src/main/java/net/openhft/chronicle/network/TcpEventHandler.java (hunk 3 above)
Comment (minborg) [reply src/main/java/net/openhft/chronicle/network/TcpEventHandler.java:77]: Indeed

**Review by minborg — APPROVED** [review]
